version: "3"
services:
  caps_oj_backend:
    container_name: caps_oj_backend
    restart: always
    build: ./caps-problem-solving-backend
    volumes:
      - /Users/doyeopkim/data/testcase:/data/testcase
      - /Users/doyeopkim/data/profile:/data/profile
    ports:
      - "3030:3000"
      - "8443:8443"
    links:
      - caps_oj_mongo_server
    depends_on:
      - caps_oj_mongo_server
  caps_oj_mongo_server:
    container_name: caps_oj_mongo_server
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=caps12345
    volumes:
      - ./mongoData:/data/db
    ports:
      - "27019:27017"
    command: mongod --auth
  caps_oj_frontend:
    container_name: caps_oj_frontend
    restart: always
    build: ./caps-problem-solving-frontend
    volumes:
      - /Users/doyeopkim/data/testcase:/data/testcase
    ports:
      - "8081:80"
    depends_on:
      - caps_oj_backend
    links:
      - caps_oj_backend
  caps_oj_judge:
    container_name: caps_oj_judge
    restart: always
    build: ./caps-problem-solving-judge-server
    volumes:
    - /Users/doyeopkim/data/testcase:/data/testcase
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    depends_on:
      - caps_oj_backend
    ports:
      - "3031:3000"
    links:
      - caps_oj_backend
    ports:
    - "2931:3000"
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE

#    cgroup_parent: m-executor-abcd
#    capabilities:
#      add: [SYS_ADMIN]